/**
 * OMEGA — Seed script.
 * Ports the v1 in-memory dataset into Postgres so the demo opens with
 * realistic content. Idempotent: safe to re-run.
 */
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('  Seeding OMEGA Postgres…');

  /* ---------------------------------------------------------------- USERS */
  const passDemo  = bcrypt.hashSync('demo1234', 8);
  const passAdmin = bcrypt.hashSync('admin1234', 8);

  const userSeeds = [
    {
      id: 'u-admin', email: 'admin@omega.mu', name: 'OMEGA Admin',
      phone: '+230 5 720 14 22', role: 'admin',
      avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=OMEGA%20Admin',
      bio: 'Compte administrateur OMEGA.', location: 'Port-Louis',
      passwordHash: passAdmin,
    },
    {
      id: 'u-demo', email: 'demo@omega.mu', name: 'Démo Utilisateur',
      phone: '+33 6 12 34 56 78', role: 'user',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=256&q=80',
      bio: 'Expatrié français installé à Grand Baie depuis 2 ans.',
      location: 'Grand Baie', passwordHash: passDemo,
    },
    // Seeded post authors — full accounts so they can be followed, messaged, etc.
    { id: 'u-claire', email: 'claire@omega.mu',  name: 'Claire Vidal',  passwordHash: passDemo,
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=128&q=80', location: 'Tamarin' },
    { id: 'u-marc',   email: 'marc@omega.mu',    name: 'Marc Dupont',   passwordHash: passDemo,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&q=80', location: 'Grand Baie' },
    { id: 'u-sophie', email: 'sophie@omega.mu',  name: 'Sophie Martin', passwordHash: passDemo,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=128&q=80', location: 'Flic-en-Flac' },
    { id: 'u-leo',    email: 'leo@omega.mu',     name: 'Léo Bernard',   passwordHash: passDemo,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&q=80', location: 'Moka' },
    { id: 'u-amelie', email: 'amelie@omega.mu',  name: 'Amélie Roche',  passwordHash: passDemo,
      avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=128&q=80', location: 'Pereybère' },
  ];
  for (const u of userSeeds) {
    await prisma.user.upsert({ where: { id: u.id }, update: u, create: u });
  }
  console.log(`    users: ${userSeeds.length}`);

  /* ----------------------------------------------------------- PROPERTIES */
  const agentElodie = { name: 'Élodie Maréchal', agency: 'OMEGA Premium Real Estate', phone: '+230 5 720 14 22', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=256&q=80' };
  const agentKarim  = { name: 'Karim Hassen',    agency: 'OMEGA Premium Real Estate', phone: '+230 5 462 88 91', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=256&q=80' };
  const agentLaure  = { name: 'Laure Pinto',     agency: 'OMEGA Premium Real Estate', phone: '+230 5 911 04 73', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=256&q=80' };

  const properties = [
    { id: 'ma7-1735', reference: 'MA7-1735', title: 'Villa contemporaine 5 pièces — vue mer', titleEn: 'Contemporary 5-room villa — sea view', type: 'Villa', transaction: 'sale', price: 1690000, location: 'Grand Baie', region: 'Nord', surface: 416, landSurface: 720, rooms: 5, bedrooms: 4, bathrooms: 4, parking: 2, yearBuilt: 2023, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80','https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=80','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80'], description: 'Magnifique villa de 416 m² au cœur de Grand Baie, dans un domaine sécurisé. Architecture contemporaine en U autour d\'une piscine privative, 4 suites avec dressing, immense terrasse vue mer et jardin tropical entretenu.', features: ['Piscine privée 10x4 m','Vue mer partielle','4 suites avec dressing','Pool house & SPA','Domotique intégrée','Climatisation gainable','Jardin paysager 720 m²','Garage double','Domaine sécurisé 24/7'], tags: ['Expat Opportunity','PDS éligible'], agent: agentElodie, featured: true, new: true, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1735/', listedAt: new Date('2026-04-22') },
    { id: 'ma7-1805', reference: 'MA7-1805', title: 'Maison familiale 4 pièces — quartier résidentiel', titleEn: '4-room family home', type: 'Maison', transaction: 'sale', price: 595000, location: 'Grand Baie', region: 'Nord', surface: 232, landSurface: 480, rooms: 4, bedrooms: 3, bathrooms: 2, parking: 2, yearBuilt: 2021, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&q=80','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=80'], description: 'Charmante maison familiale plain-pied 232 m², piscine, terrasse couverte, jardin paysager.', features: ['Piscine 7x3 m','Terrasse couverte 35 m²','Jardin paysager 480 m²','3 chambres climatisées','Carport 2 voitures'], tags: ['Expat Opportunity'], agent: agentLaure, featured: false, new: true, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1805/', listedAt: new Date('2026-04-28') },
    { id: 'ma7-1815', reference: 'MA7-1815', title: 'Villa golf 6 pièces — Beau Champ', titleEn: '6-room golf villa — Beau Champ', type: 'Villa', transaction: 'sale', price: 2350000, location: 'Beau Champ', region: 'Est', surface: 445, landSurface: 1250, rooms: 6, bedrooms: 5, bathrooms: 5, parking: 3, yearBuilt: 2022, eligibility: 'IRS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600&q=80','https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80','https://images.unsplash.com/photo-1600607687126-c2c34efe0a8d?w=1600&q=80'], description: 'Villa d\'exception 445 m² au sein d\'un domaine golfique 5 étoiles.', features: ['Vue golf 18 trous','Piscine miroir 12x5 m','Accès plage privée','5 suites','Cave à vin'], tags: ['Expat Opportunity','Investissement'], agent: agentElodie, featured: true, new: true, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1815/', listedAt: new Date('2026-04-15') },
    { id: 'ma7-1870', reference: 'MA7-1870', title: 'Appartement 4 pièces — résidence haut standing', titleEn: '4-room apartment — luxury residence', type: 'Appartement', transaction: 'sale', price: 845000, location: 'Grand Baie', region: 'Nord', surface: 215, rooms: 4, bedrooms: 3, bathrooms: 3, parking: 2, yearBuilt: 2024, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80','https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=1600&q=80'], description: 'Appartement neuf 215 m² avec terrasse 50 m² vue mer, piscine, salle de sport et conciergerie.', features: ['Terrasse 50 m² vue mer','Suite parentale avec dressing','Piscine commune & SPA','Salle de sport','Conciergerie 7j/7'], tags: ['Expat Opportunity','Neuf'], agent: agentKarim, featured: true, new: true, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1870/', listedAt: new Date('2026-05-02') },
    { id: 'ma7-1694', reference: 'MA7-1694', title: 'Villa 5 pièces — domaine sécurisé', titleEn: '5-room villa — gated estate', type: 'Villa', transaction: 'sale', price: 1820000, location: 'Grand Baie', region: 'Nord', surface: 435, landSurface: 980, rooms: 5, bedrooms: 4, bathrooms: 4, parking: 2, yearBuilt: 2022, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=80'], description: 'Villa 435 m² au sein d\'un domaine sécurisé du Nord, 4 chambres, piscine.', features: ['Piscine privée 9x4 m','Suite parentale avec terrasse','Cuisine américaine équipée','Bureau','Domaine sécurisé 24/7'], tags: [], agent: agentKarim, featured: true, new: false, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1694/', listedAt: new Date('2026-04-10') },
    { id: 'ma7-1564', reference: 'MA7-1564', title: 'Villa 5 pièces — Balaclava', titleEn: '5-room villa — Balaclava', type: 'Villa', transaction: 'sale', price: 1295000, location: 'Balaclava', region: 'Nord', surface: 300, landSurface: 650, rooms: 5, bedrooms: 4, bathrooms: 3, parking: 2, yearBuilt: 2021, eligibility: 'Smart City — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=80','https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&q=80'], description: 'Belle villa familiale 300 m² au sein d\'un Smart City à Balaclava.', features: ['Piscine privée 8x3,5 m','4 chambres climatisées','Double séjour','Smart City sécurisée'], tags: ['Smart City'], agent: agentLaure, featured: false, new: false, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1564/', listedAt: new Date('2026-03-30') },
    { id: 'ma7-1532', reference: 'MA7-1532', title: 'Appartement 4 pièces — Pointe aux Canonniers', titleEn: '4-room apartment — Pointe aux Canonniers', type: 'Appartement', transaction: 'sale', price: 549000, location: 'Pointe aux Canonniers', region: 'Nord', surface: 142, rooms: 4, bedrooms: 3, bathrooms: 2, parking: 1, yearBuilt: 2020, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600&q=80','https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=1600&q=80'], description: 'Appartement 142 m² à 200 m de la plage de Pointe aux Canonniers.', features: ['Pieds dans l\'eau','Vue lagon','Terrasse 22 m²','Piscine commune'], tags: [], agent: agentKarim, featured: false, new: false, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1532/', listedAt: new Date('2026-04-05') },
    { id: 'ma7-1490', reference: 'MA7-1490', title: 'Appartement 4 pièces — Pereybère', titleEn: '4-room apartment — Pereybère', type: 'Appartement', transaction: 'sale', price: 685000, location: 'Pereybère', region: 'Nord', surface: 189, rooms: 4, bedrooms: 3, bathrooms: 2, parking: 1, yearBuilt: 2022, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80','https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=1600&q=80'], description: 'Appartement 189 m² au dernier étage d\'une résidence intimiste à Pereybère.', features: ['Dernier étage','Vue baie panoramique','Grande terrasse','Quartier expat'], tags: [], agent: agentLaure, featured: false, new: false, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1490/', listedAt: new Date('2026-03-18') },
    { id: 'ma7-1459', reference: 'MA7-1459', title: "Appartement d'exception 8 pièces — 747 m²", titleEn: 'Exceptional 8-room apartment — 747 sqm', type: 'Appartement', transaction: 'sale', price: 4150000, location: 'Grand Baie', region: 'Nord', surface: 747, rooms: 8, bedrooms: 6, bathrooms: 6, parking: 4, yearBuilt: 2024, eligibility: 'PDS / IRS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1613553423824-58a4a08fcb98?w=1600&q=80','https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80','https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80'], description: 'Appartement trophée 747 m² sur 2 niveaux, 6 suites, terrasses 180 m² avec piscine et jacuzzi.', features: ['2 niveaux','6 suites avec dressing','Terrasses 180 m² avec piscine','Salle de cinéma','Conciergerie 5 étoiles'], tags: ['Trophée','Expat Opportunity'], agent: agentElodie, featured: true, new: true, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1459/', listedAt: new Date('2026-05-04') },
    { id: 'ma7-1448', reference: 'MA7-1448', title: 'Maison 7 pièces — domaine résidentiel', titleEn: '7-room house', type: 'Maison', transaction: 'sale', price: 1980000, location: 'Grand Baie', region: 'Nord', surface: 400, landSurface: 1100, rooms: 7, bedrooms: 5, bathrooms: 4, parking: 3, yearBuilt: 2020, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=80','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=80'], description: 'Vaste maison familiale 400 m² sur 1 100 m² de terrain.', features: ['7 pièces','Terrain 1 100 m²','Piscine 11x5 m','Pool house'], tags: [], agent: agentKarim, featured: false, new: false, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1448/', listedAt: new Date('2026-03-12') },
    { id: 'ma7-1911', reference: 'MA7-1911', title: 'Villa neuve 5 pièces — 420 m²', titleEn: 'Brand-new 5-room villa — 420 sqm', type: 'Villa', transaction: 'sale', price: 1745000, location: 'Grand Baie', region: 'Nord', surface: 420, landSurface: 850, rooms: 5, bedrooms: 4, bathrooms: 4, parking: 2, yearBuilt: 2025, eligibility: 'PDS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80','https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80'], description: 'Villa neuve 420 m² livrée 2025, signée par un architecte mauricien reconnu.', features: ['Livrée 2025','Architecte renommé','Piscine miroir','Garantie décennale'], tags: ['Neuf'], agent: agentElodie, featured: true, new: true, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1911/', listedAt: new Date('2026-05-08') },
    { id: 'ma7-1882', reference: 'MA7-1882', title: 'Penthouse 4 pièces — 400 m² vue mer', titleEn: '4-room penthouse — 400 sqm sea view', type: 'Penthouse', transaction: 'sale', price: 2890000, location: 'Grand Baie', region: 'Nord', surface: 400, rooms: 4, bedrooms: 3, bathrooms: 3, parking: 3, yearBuilt: 2024, eligibility: 'PDS / IRS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80','https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&q=80','https://images.unsplash.com/photo-1613553423824-58a4a08fcb98?w=1600&q=80'], description: 'Penthouse 4 pièces de 400 m² au dernier étage d\'une résidence iconique. Vue mer 270°.', features: ['Dernier étage','Vue mer 270°','Terrasse 120 m² avec piscine privée','Jacuzzi'], tags: ['Trophée','Expat Opportunity'], agent: agentElodie, featured: true, new: true, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1882/', listedAt: new Date('2026-05-10') },
    { id: 'ma7-1340', reference: 'MA7-1340', title: 'Villa 5 pièces — Rivière Noire', titleEn: '5-room villa — Rivière Noire', type: 'Villa', transaction: 'sale', price: 2650000, location: 'Rivière Noire', region: 'Ouest', surface: 507, landSurface: 1400, rooms: 5, bedrooms: 4, bathrooms: 4, parking: 3, yearBuilt: 2021, eligibility: 'IRS — éligible Residence Permit', images: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600&q=80','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80'], description: 'Villa 507 m² au sein d\'un domaine équestre et golf de Rivière Noire.', features: ['Vue Morne Brabant','Domaine équestre & golf','4 suites','Piscine 12x5 m'], tags: [], agent: agentKarim, featured: true, new: false, sourceUrl: 'https://www.decordier-immobilier.mu/fr/achat/ref-ma7-1340/', listedAt: new Date('2026-02-22') },
    // Locations
    { id: 'rent-gb',  reference: 'LOC-GB-001',  title: 'Villa 4 pièces meublée — location longue durée', titleEn: '4-room furnished villa — long-term rental', type: 'Villa', transaction: 'rent', price: 3800, location: 'Grand Baie', region: 'Nord', surface: 260, landSurface: 580, rooms: 4, bedrooms: 3, bathrooms: 3, parking: 2, yearBuilt: 2022, eligibility: 'Location — non éligible Residence Permit', images: ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1600&q=80','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=80'], description: 'Villa contemporaine meublée, piscine, jardin clos, à 10 min des écoles internationales.', features: ['Meublée','Piscine privée','Fibre 1 Gbps','Bail 12 ou 24 mois'], tags: ['Meublée'], agent: agentLaure, featured: true, new: true, listedAt: new Date('2026-05-09') },
    { id: 'rent-tam', reference: 'LOC-TAM-002', title: 'Villa pieds dans l\'eau — Tamarin', titleEn: 'Beachfront villa — Tamarin', type: 'Villa', transaction: 'rent', price: 6500, location: 'Tamarin', region: 'Ouest', surface: 340, landSurface: 950, rooms: 5, bedrooms: 4, bathrooms: 4, parking: 3, yearBuilt: 2024, eligibility: 'Location — non éligible Residence Permit', images: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=1600&q=80','https://images.unsplash.com/photo-1613553423824-58a4a08fcb98?w=1600&q=80'], description: 'Villa neuve en première ligne sur la baie de Tamarin.', features: ['Accès plage privée','Meublée haut de gamme','Piscine miroir','4 suites'], tags: ['Plage'], agent: agentElodie, featured: true, new: true, listedAt: new Date('2026-05-06') },
    { id: 'rent-per', reference: 'LOC-PER-003', title: 'Appartement 3 pièces meublé — Pereybère', titleEn: '3-room furnished apartment — Pereybère', type: 'Appartement', transaction: 'rent', price: 1850, location: 'Pereybère', region: 'Nord', surface: 110, rooms: 3, bedrooms: 2, bathrooms: 2, parking: 1, yearBuilt: 2021, eligibility: 'Location — non éligible Residence Permit', images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80','https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80'], description: 'Appartement 2 chambres meublé à 5 min à pied de la plage de Pereybère.', features: ['Meublé','Terrasse','Piscine commune','À 5 min de la plage'], tags: [], agent: agentLaure, featured: false, new: false, listedAt: new Date('2026-04-30') },
    { id: 'rent-fef', reference: 'LOC-FEF-004', title: 'Duplex 4 pièces front de mer — Flic-en-Flac', titleEn: 'Beachfront 4-room duplex', type: 'Duplex', transaction: 'rent', price: 3200, location: 'Flic-en-Flac', region: 'Ouest', surface: 180, rooms: 4, bedrooms: 3, bathrooms: 2, parking: 2, yearBuilt: 2019, eligibility: 'Location — non éligible Residence Permit', images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600&q=80','https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80'], description: 'Duplex en location longue durée à Flic-en-Flac, pieds dans l\'eau.', features: ['Pieds dans l\'eau','Meublé','Piscine commune','3 chambres'], tags: [], agent: agentLaure, featured: false, new: false, listedAt: new Date('2026-05-05') },
    { id: 'rent-mka', reference: 'LOC-MKA-005', title: 'Appartement neuf 3 pièces — Moka', titleEn: 'Brand-new 3-room apartment — Moka', type: 'Appartement', transaction: 'rent', price: 1650, location: 'Moka', region: 'Centre', surface: 125, rooms: 3, bedrooms: 2, bathrooms: 2, parking: 1, yearBuilt: 2023, eligibility: 'Location — non éligible Residence Permit', images: ['https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=1600&q=80','https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&q=80'], description: 'Appartement neuf au sein d\'une Smart City à Moka.', features: ['Neuf 2023','Smart City','Salle de sport','Proche Cybercity'], tags: ['Smart City'], agent: agentKarim, featured: false, new: false, listedAt: new Date('2026-04-18') },
  ];

  for (const p of properties) {
    await prisma.property.upsert({ where: { id: p.id }, update: p, create: p });
  }
  console.log(`    properties: ${properties.length}`);

  /* ------------------------------------------------------------- SERVICES */
  const services = [
    { id: 's-notaire-1',    name: 'Maître Joubert · Notaire à Grand Baie', category: 'Notaire',            description: "Notaire spécialisé dans les acquisitions immobilières PDS/IRS pour expatriés. 18 ans d'expérience à Maurice.", contact: { phone: '+230 5 422 18 30', email: 'contact@joubert-notaire.mu', website: 'https://example.mu' }, location: 'Grand Baie', rating: 4.9, reviews: 87,  subscription: 'premium',  image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80' },
    { id: 's-agence-1',     name: 'OMEGA Premium Real Estate',             category: 'Agence immobilière', description: 'Agence partenaire OMEGA. Acquisition, gestion locative et conciergerie premium à l\'île Maurice.', contact: { phone: '+230 5 720 14 22', email: 'contact@omega.mu', website: 'https://omega.mu' }, location: 'Grand Baie', rating: 5.0, reviews: 142, subscription: 'premium', image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80' },
    { id: 's-avocat-1',     name: 'Cabinet Lefèvre · Droit des affaires',   category: 'Avocat',             description: 'Spécialiste fiscalité internationale, Occupation Permit et structures offshore mauriciennes.', contact: { phone: '+230 5 311 09 22', email: 'lefevre@avocat.mu' }, location: 'Port-Louis', rating: 4.8, reviews: 53,  subscription: 'standard', image: 'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?w=800&q=80' },
    { id: 's-demenageur-1', name: 'Indian Ocean Movers',                   category: 'Déménagement',       description: 'Déménagement international Europe ↔ Maurice. Devis sous 48h, dédouanement et stockage inclus.',  contact: { phone: '+230 5 911 04 73', email: 'hello@iom.mu', website: 'https://example.mu' }, location: 'Port-Louis', rating: 4.7, reviews: 31, subscription: 'standard', image: 'https://images.unsplash.com/photo-1600518464441-9154a4dea21b?w=800&q=80' },
    { id: 's-ecole-1',      name: 'Westcoast International School',         category: 'École internationale', description: 'Programme Cambridge IGCSE / A-Level, maternelle à terminale. Bilingue FR/EN.',  contact: { phone: '+230 401 6000', email: 'admissions@westcoast.mu', website: 'https://westcoast.mu' }, location: 'Flic-en-Flac', rating: 4.8, reviews: 96, subscription: 'premium', image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80' },
    { id: 's-transport-1',  name: 'OMEGA Mobility',                        category: 'Transport',          description: 'Transferts aéroport, location longue durée avec chauffeur. Flotte premium.',  contact: { phone: '+230 5 720 99 11', email: 'mobility@omega.mu' }, location: 'Plaisance', rating: 4.9, reviews: 64, subscription: 'standard', image: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80' },
    { id: 's-banque-1',     name: 'MCB · Expat Banking',                    category: 'Banque',             description: 'Service dédié expatriés : compte multi-devises, financement immobilier non-résident.', contact: { phone: '+230 202 5000', email: 'expats@mcb.mu', website: 'https://mcb.mu' }, location: 'Port-Louis', rating: 4.6, reviews: 211, subscription: 'premium', image: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80' },
    { id: 's-medecin-1',    name: 'Wellkin Hospital · Médecins anglophones',category: 'Santé',              description: 'Cliniques privées avec médecins francophones et anglophones. Convention assurances.',  contact: { phone: '+230 605 1000', email: 'info@wellkin.mu', website: 'https://wellkin.mu' }, location: 'Moka', rating: 4.7, reviews: 178, subscription: 'standard', image: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=800&q=80' },
  ];
  for (const s of services) {
    await prisma.service.upsert({ where: { id: s.id }, update: s, create: s });
  }
  console.log(`    services: ${services.length}`);

  /* ---------------------------------------------------------------- GUIDES */
  const guides = [
    { id: 'g-visa',     slug: 'visa-premium-residence',  title: 'Visa & Permis de Résidence Premium', titleEn: 'Premium Residence Permit', category: 'Administratif', icon: 'FileText',     color: 'sky',     coverImage: 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?w=1200&q=80', description: "Tout ce qu'il faut savoir pour obtenir votre Premium Visa ou Residence Permit.", descriptionEn: 'Everything you need to know about the Premium Visa and Residence Permits.', readTime: 8,  steps: [{title:'Vérifier votre éligibilité',body:'Le Premium Travel Visa s\'adresse aux personnes pouvant justifier de revenus mensuels supérieurs à 1 500 USD.'},{title:'Préparer les pièces justificatives',body:'Passeport, justificatifs de revenus, attestation d\'assurance santé internationale, billet retour, preuve d\'hébergement.'},{title:'Déposer la demande en ligne',body:'Tout passe par le portail EDB Mauritius. 10 à 15 jours ouvrés pour le Premium Visa.'},{title:'Récupérer votre permis',body:'À l\'arrivée, présentez-vous au Passport & Immigration Office à Port-Louis.'}], tips: ['Faire traduire vos documents par un traducteur assermenté avant le départ.','Conserver les justificatifs de revenus en PDF natif.','Préférer une assurance santé qui couvre explicitement Maurice.'] },
    { id: 'g-logement', slug: 'trouver-logement',        title: 'Trouver un logement à Maurice',      titleEn: 'Finding a home in Mauritius', category: 'Immobilier', icon: 'Home',        color: 'teal',    coverImage: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80', description: 'Quartiers, prix moyens, pièges à éviter et plateformes fiables.', descriptionEn: 'Neighborhoods, average prices and trusted platforms.', readTime: 12, steps: [{title:'Choisir votre zone',body:'Grand Baie, Tamarin, Black River, Pereybère et Flic-en-Flac concentrent la majorité des expatriés.'},{title:'Comprendre les statuts',body:'PDS, IRS, RES, Smart City : régimes permettant à un non-citoyen d\'acheter.'},{title:'Visiter et négocier',body:'Les prix sont quasiment toujours négociables (5 à 10 %).'},{title:'Signer le compromis',body:'Toujours passer par un notaire mauricien.'}], tips: ['Visiter en saison des pluies pour détecter humidité.','Demander la facture EDB des 3 derniers mois.','Vérifier la connexion fibre avant signature.'] },
    { id: 'g-banque',   slug: 'ouvrir-compte-bancaire',  title: 'Ouvrir un compte bancaire',          titleEn: 'Opening a bank account', category: 'Finance', icon: 'Landmark',    color: 'indigo',  coverImage: 'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=1200&q=80', description: 'MCB, SBM, ABC Banking, Absa : comparatif et démarches.', descriptionEn: 'MCB, SBM, ABC Banking, Absa: comparison and steps.', readTime: 6,  steps: [{title:'Choisir la banque',body:'MCB et SBM sont les deux poids lourds.'},{title:'Préparer le dossier',body:'Passeport, permis de résidence, justificatif d\'adresse, 2 références bancaires.'},{title:'Prendre rendez-vous en agence',body:'La présence physique est obligatoire pour la signature.'},{title:'Activer carte et e-banking',body:'La carte arrive par courrier sous 7 à 10 jours.'}], tips: ['Ouvrir un compte en MUR et un compte en EUR/USD.','Demander la « Juice MCB » pour les paiements quotidiens.'] },
    { id: 'g-sante',    slug: 'systeme-sante',           title: 'Comprendre le système de santé',     titleEn: 'Healthcare system explained', category: 'Santé', icon: 'HeartPulse',  color: 'rose',    coverImage: 'https://images.unsplash.com/photo-1538108149393-fbbd81895907?w=1200&q=80', description: 'Cliniques privées, hôpitaux publics, assurances internationales.', descriptionEn: 'Private clinics, public hospitals, international insurance.', readTime: 7,  steps: [{title:'Choisir une assurance santé',body:'April International, Cigna et MSH sont les plus utilisées.'},{title:'Identifier les cliniques de référence',body:'Wellkin, Clinique Darné, Apollo Bramwell, C-Care.'},{title:'Constituer une trousse d\'urgence',body:'Numéro assurance, SAMU 114, médecin référent.'}], tips: ['Demander un devis avant tout acte non urgent.','Pharmacie de garde fiable au Nord : New Pharmacy.'] },
    { id: 'g-ecole',    slug: 'ecoles-internationales',  title: 'Scolariser ses enfants',             titleEn: 'Schooling your children', category: 'Éducation', icon: 'GraduationCap', color: 'amber',   coverImage: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&q=80', description: "Lycée français, IB, Cambridge : trouver l'établissement adapté.", descriptionEn: 'French Lycée, IB schools, Cambridge schools.', readTime: 9,  steps: [{title:'Cartographier les options',body:'Lycée Français, Lycée La Bourdonnais, Northfields, Le Bocage, IPS, Westcoast.'},{title:'Anticiper les listes d\'attente',body:'Inscriptions à ouvrir entre janvier et mars pour la rentrée d\'août.'},{title:'Préparer le dossier',body:'Livret scolaire, certificat de scolarité, bulletin de santé.'}], tips: ['La Bourdonnais offre les meilleurs résultats au bac.','Westcoast très réputé pour le bilinguisme.'] },
    { id: 'g-permis',   slug: 'permis-de-conduire',      title: 'Permis de conduire & véhicule',      titleEn: 'Driving license & buying a car', category: 'Mobilité', icon: 'Car',         color: 'violet',  coverImage: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=1200&q=80', description: 'Conversion du permis, achat d\'occasion, importation.', descriptionEn: 'License conversion, used cars, importation.', readTime: 6,  steps: [{title:'Convertir votre permis',body:'Permis français/UE utilisable 12 mois. Conversion au Traffic Branch après.'},{title:'Acheter une voiture',body:'Privilégier des modèles japonais reconditionnés (Toyota, Suzuki, Honda).'},{title:'Assurer le véhicule',body:'Swan, Mauritius Union et NIC sont les leaders.'}], tips: ['Conduire à gauche.','Vérifier le horsepower tax avant achat.'] },
    { id: 'g-fiscalite',slug: 'fiscalite-expatries',     title: 'Fiscalité des expatriés',            titleEn: 'Tax basics for expats', category: 'Finance', icon: 'Calculator',  color: 'emerald', coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1200&q=80', description: 'Convention fiscale, IR à 15 %, résidence fiscale.', descriptionEn: 'Tax treaty, flat 15% IR, tax residency.', readTime: 10, steps: [{title:'Déterminer votre résidence fiscale',body:'183 jours sur place ou centre des intérêts économiques à Maurice.'},{title:'Anticiper les déclarations',body:'Année fiscale du 1er juillet au 30 juin. MRA avant fin septembre.'},{title:'Optimiser via le Premium Visa',body:'Imposé uniquement sur les revenus rapatriés à Maurice.'}], tips: ['Consulter un fiscaliste local avant la première déclaration.','Tenir un journal des entrées/sorties du territoire.'] },
  ];
  for (const g of guides) {
    await prisma.guide.upsert({ where: { id: g.id }, update: g, create: g });
  }
  console.log(`    guides: ${guides.length}`);

  /* ----------------------------------------------------------------- POSTS */
  const postSeeds = [
    { id: 'p-seed-1', authorId: 'u-claire', content: "Premier mois à Tamarin : la fibre Mauritius Telecom a été activée en 4 jours, un record. Si quelqu'un cherche un électricien fiable pour installer une clim, je recommande Yan (whatsapp en MP) — propre, ponctuel, prix correct.", image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&q=80', tag: 'Installation', createdAt: new Date('2026-05-11T08:24:00Z') },
    { id: 'p-seed-2', authorId: 'u-marc',   content: "Petite victoire administrative : Occupation Permit obtenu en 18 jours via l'EDB ! Le dossier a été accepté du premier coup. Astuce : faire traduire le casier judiciaire en France, ça gagne 2 semaines.", image: null, tag: 'Administratif', createdAt: new Date('2026-05-10T17:02:00Z') },
    { id: 'p-seed-3', authorId: 'u-sophie', content: "Bonne adresse du week-end : « La Table de Patrick », petit restaurant créole tenu en famille à Flic-en-Flac. Vivaneau grillé, rougail saucisses maison, addition à 800 MUR pour 2. À tester !", image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=80', tag: 'Lifestyle', createdAt: new Date('2026-05-09T19:50:00Z') },
    { id: 'p-seed-4', authorId: 'u-leo',    content: "Question ouverte aux parents : Northfields ou Le Bocage pour un CE2 ? On hésite, et les listes d'attente sont serrées. Vos retours ?", image: null, tag: 'École', createdAt: new Date('2026-05-08T10:14:00Z') },
    { id: 'p-seed-5', authorId: 'u-amelie', content: "Petite alerte : attention aux annonces immobilières trop alléchantes sur Facebook. J'ai failli verser un acompte à un faux propriétaire. Toujours passer par notaire et vérifier le titre foncier !", image: null, tag: 'Immobilier', createdAt: new Date('2026-05-07T14:30:00Z') },
  ];
  for (const p of postSeeds) {
    await prisma.post.upsert({ where: { id: p.id }, update: p, create: p });
  }
  console.log(`    posts: ${postSeeds.length}`);

  /* --------------------------------------------------------- LEAD SAMPLES */
  const leadSeeds = [
    { id: 'l-seed-1', type: 'property', propertyId: 'ma7-1882',
      name: 'Antoine Lefranc', email: 'antoine.lefranc@example.com', phone: '+33 6 88 12 45 33',
      message: 'Intéressé par le penthouse Grand Baie — budget 2-3M€. Disponible pour visite semaine prochaine.',
      source: 'property-card', interest: 'real-estate', status: 'new',
      createdAt: new Date('2026-05-11T14:22:00Z') },
    { id: 'l-seed-2', type: 'general',  name: 'Marie-Hélène Cartier', email: 'mh.cartier@example.com', phone: '+33 6 12 99 04 22',
      message: 'Souhaite rejoindre la communauté avant son déménagement en septembre.',
      source: 'landing-section', interest: 'community', status: 'contacted',
      createdAt: new Date('2026-05-09T09:14:00Z') },
    { id: 'l-seed-3', type: 'service',  serviceId: 's-notaire-1',
      name: 'Pierre Lambert', email: 'p.lambert@example.com', phone: '+230 5 422 18 33',
      message: 'Devis pour acquisition PDS à Grand Baie. Compromis de vente prévu mi-juin.',
      source: 'service-directory', interest: 'service:s-notaire-1', status: 'new',
      createdAt: new Date('2026-05-12T11:08:00Z') },
  ];
  for (const l of leadSeeds) await prisma.lead.upsert({ where: { id: l.id }, update: l, create: l });
  console.log(`    leads: ${leadSeeds.length}`);

  console.log('  ✔ seed complete.');
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
